Fix manage.py to work with argh 0.30+.
Full traceback with info:

```
$ bin/manage -h
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/bin/manage", line 63, in <module>
    sys.exit(plone.releaser.manage.manage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 277, in __call__
    parser.add_commands(
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/helpers.py", line 47, in add_commands
    return add_commands(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 592, in add_commands
    set_default_command(
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 331, in set_default_command
    inferred_args: List[ParserAddArgumentSpec] = list(
                                                 ^^^^^
  File "/Users/maurits/shared-eggs/cp312/argh-0.30.2-py3.12.egg/argh/assembling.py", line 155, in infer_argspecs_from_function
    raise ArgumentNameMappingError(
argh.assembling.ArgumentNameMappingError: Argument "path" in function "add_checkout"
is not keyword-only but has a default value.

Please note that since Argh v.0.30 the default name mapping
policy has changed.

More information:
https://argh.readthedocs.io/en/latest/changes.html#version-0-30-0-2023-10-21

You need to upgrade your functions so that the arguments
that have default values become keyword-only:

    f(x=1) -> f(*, x=1)

If you actually want an optional positional argument,
please set the name mapping policy explicitly to `BY_NAME_IF_KWONLY`.

If you choose to postpone the migration, you have two options:

a) set the policy explicitly to `BY_NAME_IF_HAS_DEFAULT`;
b) pin Argh version to 0.29 until you are ready to migrate.

Thank you for understanding!
```