Removed no longer working pulls command that I have never used.
Removed `PyGithub` and `keyring` dependencies that was only used for this.
Removed `Source.path` property that was only used for this.

Traceback when you try the `pulls` command:

```
$ bin/manage pulls
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/bin/manage", line 69, in <module>
    sys.exit(plone.releaser.manage.manage())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 271, in __call__
    parser.dispatch()
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/helpers.py", line 54, in dispatch
    return dispatch(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 179, in dispatch
    for line in lines:
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 290, in _execute_command
    for line in result:
  File "/Users/maurits/shared-eggs/cp311/argh-0.28.1-py3.11.egg/argh/dispatching.py", line 273, in _call
    result = function(*positional, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/manage.py", line 94, in pulls
    g = Github(client_id=client_id, client_secret=client_secret)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Github.__init__() got an unexpected keyword argument 'client_id'
```