Configuring with plone.meta: use 6.2 constraints.
Locally with 6.0 I got this error when running the tests:

```
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.releaser/.tox/test/lib/python3.13/site-packages/pytest_plone/helpers.py", line 1, in <module>
    import gocept.pytestlayer.fixture
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.releaser/.tox/test/lib/python3.13/site-packages/gocept/pytestlayer/__init__.py", line 1, in <module>
    raise RuntimeError("'gocept.pytestlayer' is deprecated."
                       " Please use 'zope.pytestlayer' instead."
                       " They are compatible besides the name.")
RuntimeError: 'gocept.pytestlayer' is deprecated. Please use 'zope.pytestlayer' instead. They are compatible besides the name.
```

Strangely, on GitHub Actions is was fine.